"use strict";
var express_1 = require('express');
var home_1 = require('./home');
var user_1 = require('./user');
var post_1 = require('./post');
// import login from './login';
// import admin from './admin';
// import postDetail from './post_detail';
// import tag from './tag';
var router = express_1.Router();
router.use('/', home_1.home);
router.use(user_1.user);
router.use(post_1.post_router);
exports.__esModule = true;
exports["default"] = router;
